name: Build and Publish
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "8"
      - name: Run Unit Tests
        run: ./mvnw --no-transfer-progress clean test
      - name: Package
        run: ./mvnw --no-transfer-progress clean package -DskipTests
